### PR TITLE
Always add backticks to tag

### PR DESCRIPTION
**Pull request by ruudk**
We use `@todo` as tag, and it's annoying that now this tags username `todo` ;)

### CODE REVIEW

**Comment by ruudk** [comment]
I assume a test will fail, but I cannot see it immediately because the workflow needs to be approved.

**Comment by gkampitakis** [comment]
Hey 👋  thanks for the pr but I am wondering you can't pass the tag with the backticks in the input it doesn't render correctly ?

**Comment by ruudk** [comment]
But then the script will search for  \`@todo\` ?

**Comment by gkampitakis** [comment]
Ahh 💡  I see. Not going to lie haven't looked into this code for a long time 😅 . Wondering if it makes more sense to add the backticks only if the tag contains `@` instead of changing everything. Can't recall how it renders.

**Pull request closed without merging**
